### ISSUE TITLE
Removes selected class from other document items

### ISSUE THREAD

**Issue by masbaehr** [MathiasWP/CalendarPickerJS#4]
Noticed this bug:

`document.querySelectorAll('.selected')`

It should not scan the document, but only the selected classes within it's scope, as it will else remove the selected class from other stuff as well

**Comment by MathiasWP** [comment]
True, the selector should be scoped. There's no secure scoping currently implemented, but making the selector be `#calendar #calendar-grid .selected` can be a sort of quick-fix.
